-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 16:52:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`act`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`act` ;

CREATE TABLE IF NOT EXISTS `mydb`.`act` (
  `idact` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `idband` VARCHAR(45) NULL,
  PRIMARY KEY (`idact`),
  CONSTRAINT `fk_act_sets1`
    FOREIGN KEY (`idact`)
    REFERENCES `mydb`.`sets` (`idact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_act_entree1`
    FOREIGN KEY (`idact`)
    REFERENCES `mydb`.`entree` (`idact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bands` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bands` (
  `idband` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `herkomst` DATE NULL,
  `omschrijving` VARCHAR(45) NULL,
  `prijs` INT NULL,
  `bandscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idband`),
  CONSTRAINT `fk_bands_act`
    FOREIGN KEY (`idband`)
    REFERENCES `mydb`.`act` (`idband`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bands_leden1`
    FOREIGN KEY (`idband`)
    REFERENCES `mydb`.`leden` (`idband`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entree` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entree` (
  `identree` INT NOT NULL,
  `idact` INT NULL,
  `prijs` VARCHAR(45) NULL,
  `idklant` INT NULL,
  `klant_idklant` INT NOT NULL,
  PRIMARY KEY (`identree`),
  INDEX `fk_entree_klant1_idx` (`klant_idklant` ASC) VISIBLE,
  CONSTRAINT `fk_entree_klant1`
    FOREIGN KEY (`klant_idklant`)
    REFERENCES `mydb`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`klant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`klant` (
  `idklant` INT NOT NULL,
  `postcode` VARCHAR(45) NULL,
  `woonplaats` VARCHAR(45) NULL,
  `drank-kosten` INT NULL,
  PRIMARY KEY (`idklant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`leden` ;

CREATE TABLE IF NOT EXISTS `mydb`.`leden` (
  `idleden` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `tussenvoegsels` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefoonnummer` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `idband` INT NULL,
  PRIMARY KEY (`idleden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sets` (
  `idsets` INT NOT NULL,
  `sets` INT NULL,
  `tijd` VARCHAR(45) NULL,
  `idact` INT NULL,
  PRIMARY KEY (`idsets`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
