-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 16:53:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ToolsForEver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ToolsForEver` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ToolsForEver` (
  `idtoolsforever` INT NOT NULL,
  `toolsforeverlocatie` VARCHAR(45) NULL,
  `toolsforeveradres` VARCHAR(45) NULL,
  `toolsforeverhuisnummer` VARCHAR(45) NULL,
  `toolsforeverpostcode` VARCHAR(45) NULL,
  PRIMARY KEY (`idtoolsforever`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bestel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bestel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bestel` (
  `idbestel` INT NOT NULL,
  `idtoolsforever` INT NULL,
  `product` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `minimumaantal` VARCHAR(45) NULL,
  `fabriek` VARCHAR(45) NULL,
  `idvoorraad` INT NULL,
  PRIMARY KEY (`idbestel`),
  INDEX `fk_bestel_ToolsForEver1_idx` (`idtoolsforever` ASC) VISIBLE,
  CONSTRAINT `fk_bestel_ToolsForEver1`
    FOREIGN KEY (`idtoolsforever`)
    REFERENCES `mydb`.`ToolsForEver` (`idtoolsforever`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bestel_has_voorraad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bestel_has_voorraad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bestel_has_voorraad` (
  `bestel_idbestel` INT NOT NULL,
  `voorraad_idvoorraad` INT NOT NULL,
  PRIMARY KEY (`bestel_idbestel`, `voorraad_idvoorraad`),
  INDEX `fk_bestel_has_voorraad_voorraad1_idx` (`voorraad_idvoorraad` ASC) VISIBLE,
  INDEX `fk_bestel_has_voorraad_bestel1_idx` (`bestel_idbestel` ASC) VISIBLE,
  CONSTRAINT `fk_bestel_has_voorraad_bestel1`
    FOREIGN KEY (`bestel_idbestel`)
    REFERENCES `mydb`.`bestel` (`idbestel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bestel_has_voorraad_voorraad1`
    FOREIGN KEY (`voorraad_idvoorraad`)
    REFERENCES `mydb`.`voorraad` (`idvoorraad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `idlogin` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  `idtoolsforever` VARCHAR(45) NULL,
  `medewerker_idmedewerker` INT NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_medewerker1_idx` (`medewerker_idmedewerker` ASC) VISIBLE,
  INDEX `fk_login_ToolsForEver1_idx` (`idtoolsforever` ASC) VISIBLE,
  CONSTRAINT `fk_login_medewerker1`
    FOREIGN KEY (`medewerker_idmedewerker`)
    REFERENCES `mydb`.`medewerker` (`idmedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_ToolsForEver1`
    FOREIGN KEY (`idtoolsforever`)
    REFERENCES `mydb`.`ToolsForEver` (`idtoolsforever`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medewerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medewerker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medewerker` (
  `idmedewerker` INT NOT NULL,
  `medewerkernaam` VARCHAR(45) NULL,
  `medewerkertussenvoegsels` VARCHAR(45) NULL,
  `medewerkerachternaam` VARCHAR(45) NULL,
  `medewerkeremail` VARCHAR(45) NULL,
  `idlogin` INT NULL,
  PRIMARY KEY (`idmedewerker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`voorraad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`voorraad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`voorraad` (
  `idvoorraad` INT NOT NULL,
  `idtoolsforever` INT NULL,
  `product` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `inkoopprijs` VARCHAR(45) NULL,
  `verkoopprijs` VARCHAR(45) NULL,
  `fabriek` VARCHAR(45) NULL,
  `aantal` INT NULL,
  PRIMARY KEY (`idvoorraad`),
  INDEX `fk_voorraad_ToolsForEver_idx` (`idtoolsforever` ASC) VISIBLE,
  CONSTRAINT `fk_voorraad_ToolsForEver`
    FOREIGN KEY (`idtoolsforever`)
    REFERENCES `mydb`.`ToolsForEver` (`idtoolsforever`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
