-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 16:52:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`autos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`autos` (
  `idautos` INT NOT NULL,
  `auto` VARCHAR(45) NULL,
  `prijs` VARCHAR(45) NULL,
  `telefoonnummer` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `contactemail` VARCHAR(45) NULL,
  `beschrijving` VARCHAR(45) NULL,
  PRIMARY KEY (`idautos`),
  CONSTRAINT `fk_autos_huren1`
    FOREIGN KEY (`idautos`)
    REFERENCES `mydb`.`huren` (`idautos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`huren`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`huren` ;

CREATE TABLE IF NOT EXISTS `mydb`.`huren` (
  `idhuren` INT NOT NULL,
  `datum` VARCHAR(45) NULL,
  `totaalprijs` VARCHAR(45) NULL,
  `idautos` INT NULL,
  `idklant` INT NULL,
  PRIMARY KEY (`idhuren`),
  INDEX `fk_huren_klant1_idx` (`idklant` ASC) VISIBLE,
  CONSTRAINT `fk_huren_klant1`
    FOREIGN KEY (`idklant`)
    REFERENCES `mydb`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inlog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inlog` (
  `idinlog` INT NOT NULL,
  `idmedewerker` INT NULL,
  `medewerkeremail` VARCHAR(45) NULL,
  `medewerkerwachtwoord` VARCHAR(45) NULL,
  `medewerker_idmedewerker` INT NOT NULL,
  PRIMARY KEY (`idinlog`),
  INDEX `fk_inlog_medewerker_idx` (`medewerker_idmedewerker` ASC) VISIBLE,
  CONSTRAINT `fk_inlog_medewerker`
    FOREIGN KEY (`medewerker_idmedewerker`)
    REFERENCES `mydb`.`medewerker` (`idmedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inlog_has_autos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inlog_has_autos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inlog_has_autos` (
  `inlog_idinlog` INT NOT NULL,
  `autos_idautos` INT NOT NULL,
  PRIMARY KEY (`inlog_idinlog`, `autos_idautos`),
  INDEX `fk_inlog_has_autos_autos1_idx` (`autos_idautos` ASC) VISIBLE,
  INDEX `fk_inlog_has_autos_inlog1_idx` (`inlog_idinlog` ASC) VISIBLE,
  CONSTRAINT `fk_inlog_has_autos_inlog1`
    FOREIGN KEY (`inlog_idinlog`)
    REFERENCES `mydb`.`inlog` (`idinlog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inlog_has_autos_autos1`
    FOREIGN KEY (`autos_idautos`)
    REFERENCES `mydb`.`autos` (`idautos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`klant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`klant` (
  `idklant` INT NOT NULL,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsels` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefoonnummer` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  PRIMARY KEY (`idklant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medewerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medewerker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medewerker` (
  `idmedewerker` INT NOT NULL,
  `medewerkervoornaam` VARCHAR(45) NULL,
  `medewerkertussenvoegsels` VARCHAR(45) NULL,
  `medewerkerachternaam` VARCHAR(45) NULL,
  `medewerkeremail` VARCHAR(45) NULL,
  `medewerkerwachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedewerker`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
